In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip



   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 2.2 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.6 MB 1.8 MB/s eta 0:00:07
   ---- ----------------------------------- 1.6/12.6 MB 2.0 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.6 MB 2.2 MB/s eta 0:00:05
   --------- ------------------------------ 2.9/12.6 MB 2.5 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.6 MB 2.9 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.6 MB 3.2 MB/s eta 0:00:03
   ------------------- -------------------- 6.3/12.6 MB 3.5 MB/s eta 0:00:02
   ------------------------ --------------- 7.6/12.6 MB 3.8 MB/s eta 0:00:02
   ----------------------------- ---------- 9.4/12.6 MB 4.3 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.6 MB 4.5 MB/s eta 0:00:01
   --------

In [3]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [6]:
# write your code here ^_^
x=np.ones(4)
x

array([1., 1., 1., 1.])

## Q#2: Create y array with elements equal to 0.

In [8]:
# write your code here ^_^
y=np.zeros(4)
y

array([0., 0., 0., 0.])

## Q#3: Add x and y arrays.

In [9]:
# write your code here ^_^
x+y

array([1., 1., 1., 1.])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type).

In [14]:
# write your code here ^_^
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

1
(4,)
4
float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [17]:
# write your code here ^_^
w=np.array([[11,12],
            [13,14], 
            [15, 16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [18]:
# write your code here ^_^
z = np.arange(1, 4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in horizontal way then save it in a new variable "newArray".

In [44]:
# write your code here ^_^
z_reshaped = z.reshape(-1, 1)
newArray = np.hstack((z_reshaped, w))
print("z_reshaped",z_reshaped)
print("____________________")
print(newArray)


z_reshaped [[1]
 [2]
 [3]]
____________________
[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]


## Q#8: Print all elements of "newArray" using the loop.

In [45]:
# write your code here ^_^
for row in newArray:
    for element in row:
        print(element)


1
11
12
2
13
14
3
15
16


## Q#9: Reverse the columns and rows of "newArray".

In [46]:
# write your code here ^_^
reversedArray = newArray[::-1, ::-1]
print(newArray)
print  ("------------------------")
print(reversedArray)

[[ 1 11 12]
 [ 2 13 14]
 [ 3 15 16]]
------------------------
[[16 15  3]
 [14 13  2]
 [12 11  1]]


## Q#10: Decrement all elements of "newArray" with 1.

In [47]:
# write your code here ^_^
newArray=newArray-1
newArray

array([[ 0, 10, 11],
       [ 1, 12, 13],
       [ 2, 14, 15]])

## Q#11: Find smallest and biggest values in "newArray".

In [48]:
# write your code here ^_^
print(newArray.min())
print(newArray.max())

0
15


## Q#12: Print the first row of "newArray" using indexing.

In [49]:
# write your code here ^_^
print(newArray[0])

[ 0 10 11]


## Q#13: Print the number equals 12 of "newArray" using indexing.

In [53]:
# write your code here ^_^
print(newArray[1, 1])

12 14


## Q#14: Print the numbers equal 0 and 13 of "newArray" using indexing.

In [55]:
# write your code here ^_^
print(newArray[0,0], newArray[1,2])

0 13


## Q#15: Change the shape of "newArray" to (9,1).

In [58]:
# write your code here ^_^
newArray=newArray.reshape(9,1)
newArray

array([[ 0],
       [10],
       [11],
       [ 1],
       [12],
       [13],
       [ 2],
       [14],
       [15]])

## Q#16: Change the shape of "newArray" to (3,2).

In [62]:
# write your code here ^_^
newArray_reshaped = newArray.reshape(3, 2)
print(newArray_reshaped)


ValueError: cannot reshape array of size 9 into shape (3,2)

# Well Done 🎉